Simplify arguments parsing by removing github token from the new CLI

diff --git a/bin/comment_on_pr b/bin/comment_on_pr
--- a/bin/comment_on_pr
+++ b/bin/comment_on_pr
@@ -3,17 +3,20 @@
 # This script is used to comment on a pull request, and must be run in a buldkite PR step.
 #
 # Usage:
+#    [GITHUB_TOKEN=<token>] comment_on_pr [--id <comment-id>] [--if-exist update|delete] [--github-token <token>] <comment>
 #
-#    # Post a new comment to the PR
-#    comment_on_pr "This is a comment" <github-token>
+# Examples:
 #
 #    # Post a new comment which can be uniqly identifiered by the given comment id,
 #    # or update the existing comment that's associated with the given comment id.
 #    # You can choose to delete the existing comment if it exists by passing `--if-exist delete`.
-#    comment_on_pr --id comment-id "This is a comment" [--if-exist update|delete] <github-token>
+#    comment_on_pr --id comment-id [--if-exist update|delete] "This is a comment"
 #
 #    # Delete the comment associated with the given comment id
-#    comment_on_pr --id comment-id <github-token>
+#    comment_on_pr --id comment-id [--if-exist delete]
+#
+#    # Deprecated: Post a new comment to the PR
+#    comment_on_pr "This is a comment" <github-token>
 #
 # Please note the comment argument can be a path to a file containing the comment, or a markdown.
 
@@ -35,39 +38,46 @@ fi
 # Default options
 opt_comment_id=""
 opt_if_exist="update"
+opt_github_token="${GITHUB_TOKEN-:}"
 
-while [[ "$#" -gt 0 ]]; do
-    case $1 in
-        --id) opt_comment_id="$2"; shift ;;
-        --if-exist) opt_if_exist="$2"; shift ;;
-        --*) echo "Unknown option: $1"; exit 1 ;;
-        *) break ;;
+# If there are two arguments and they don't start with an option, then we assume
+# this utility is called in the deprecated way: comment_on_pr <comment> <github-token>
+if [[ $# == 2 && "$1" != "--" ]]; then
+    if [[ -f "$1" ]]; then
+        arg_pr_comment=$(cat "$1")
+    else
+        arg_pr_comment="$1"
+    fi
+
+    opt_github_token=$2
+else
+    while [[ "$#" -gt 0 ]]; do
+        case $1 in
+            --id) opt_comment_id="$2"; shift ;;
+            --if-exist) opt_if_exist="$2"; shift ;;
+            --github-token) opt_github_token="$2"; shift ;;
+            --*) echo "Unknown option: $1"; exit 1 ;;
+            *) break ;;
+        esac
+        shift
+    done
+
+    case "$#" in
+        0)
+            arg_pr_comment=""
+            ;;
+        1)
+            if [[ -f "$1" ]]; then
+                arg_pr_comment=$(cat "$1")
+            else
+                arg_pr_comment="$1"
+            fi
+            ;;
+        *) echo "Error: invalid comment argument"; exit 1 ;;
     esac
-    shift
-done
+fi
 
-case "$#" in
-    0)
-        arg_pr_comment=""
-        arg_github_token=${GITHUB_TOKEN}
-        ;;
-    1)
-        arg_pr_comment=""
-        arg_github_token=$1
-        ;;
-    2)
-        if [[ -f "$1" ]]; then
-            arg_pr_comment=$(cat "$1")
-        else
-            arg_pr_comment="$1"
-        fi
-
-        arg_github_token=$2
-        ;;
-    *) echo "Error: invalid comment argument"; exit 1 ;;
-esac
-
-export GITHUB_TOKEN="$arg_github_token"
+export GITHUB_TOKEN="$opt_github_token"
 
 github_user=$(basename "$(dirname "${BUILDKITE_PULL_REQUEST_REPO%.git}")")
 github_repo=$(basename "${BUILDKITE_PULL_REQUEST_REPO%.git}")
