Update `run_swiftlint` to allow for custom .swiftlint config files (#189)
* Update run_swiftlint to allow for custom .swiftlint config files

* Update CHANGELOG

* Allow multiple --config flags

* Update changelog

* Remove default `--config` as SwiftLint will already use that file by default

diff --git a/bin/run_swiftlint b/bin/run_swiftlint
--- a/bin/run_swiftlint
+++ b/bin/run_swiftlint
@@ -3,6 +3,7 @@
 echo "--- :swift: Running SwiftLint"
 
 SWIFTLINT_ARGUMENTS=(--quiet --reporter relative-path)
+CONFIG_FILES=()
 
 while [[ "$#" -gt 0 ]]; do
   case $1 in
@@ -10,19 +11,44 @@ while [[ "$#" -gt 0 ]]; do
       SWIFTLINT_ARGUMENTS+=("$1")
       shift
       ;;
+    --config)
+      if [[ -z "$2" || "$2" =~ ^- ]]; then
+        echo "Error: --config requires a config file path"
+        echo "Usage: $0 [--strict | --lenient] [--config CONFIG_FILE]..."
+        exit 1
+      fi
+      CONFIG_FILES+=("$2")
+      SWIFTLINT_ARGUMENTS+=(--config "$2")
+      shift 2
+      ;;
     *) break ;;
   esac
 done
 
 if [[ $# -gt 0 ]]; then
   echo "Error: invalid arguments."
-  echo "Usage: $0 [--strict | --lenient]"
+  echo "Usage: $0 [--strict | --lenient] [--config CONFIG_FILE]..."
   exit 1
 fi
 
-SWIFTLINT_VERSION="$(<.swiftlint.yml awk '/^swiftlint_version: / {print $2}')"
+# If no config files specified, use default
+if [[ ${#CONFIG_FILES[@]} -eq 0 ]]; then
+  CONFIG_FILES=(".swiftlint.yml")
+fi
+
+# Validate all config files exist
+for config_file in "${CONFIG_FILES[@]}"; do
+  if [[ ! -f "$config_file" ]]; then
+    echo "Error: config file '$config_file' not found."
+    exit 1
+  fi
+done
+
+# Use the first config file to determine SwiftLint version
+FIRST_CONFIG_FILE="${CONFIG_FILES[0]}"
+SWIFTLINT_VERSION="$(<"$FIRST_CONFIG_FILE" awk '/^swiftlint_version: / {print $2}')"
 if [ -z "$SWIFTLINT_VERSION" ]; then
-  echo "Your \`.swiftlint.yml\` file must contain a key for \`swiftlint_version:\` so that we know which version of SwiftLint to use to lint your codebase."
+  echo "Your \`$FIRST_CONFIG_FILE\` file must contain a key for \`swiftlint_version:\` so that we know which version of SwiftLint to use to lint your codebase."
   exit 1
 fi
 SWIFTLINT_DOCKER_CMD=(docker run --rm -v "$PWD":/workspace -w /workspace ghcr.io/realm/swiftlint:"$SWIFTLINT_VERSION" swiftlint)
