Limit the SwiftLint arguments to "strict" and "lenient"

diff --git a/bin/run_swiftlint b/bin/run_swiftlint
--- a/bin/run_swiftlint
+++ b/bin/run_swiftlint
@@ -1,12 +1,30 @@
 #!/bin/bash -eu
 
+validation_error() {
+  echo "Error: invalid arguments."
+  echo "Usage: $0 [--strict | --lenient]"
+  exit 1
+}
+
 echo "--- :swift: Running SwiftLint"
+
+SWIFTLINT_ARGUMENT=""
+
+if [ "$#" -eq 1 ]; then
+  if [ "$1" == "--strict" ] || [ "$1" == "--lenient" ]; then
+    SWIFTLINT_ARGUMENT=$1
+  else
+    validation_error
+  fi
+elif [ "$#" -gt 1 ]; then
+  validation_error
+fi
 
 SWIFTLINT_VERSION=$(<.swiftlint.yml awk '/^swiftlint_version: / {print $2}')
 SWIFTLINT_CMD="docker run --rm -v $PWD:/workspace -w /workspace ghcr.io/realm/swiftlint:$SWIFTLINT_VERSION swiftlint"
 
 set +e
-SWIFTLINT_OUTPUT=$($SWIFTLINT_CMD lint --quiet "$@" --reporter relative-path)
+SWIFTLINT_OUTPUT=$($SWIFTLINT_CMD lint --quiet "$SWIFTLINT_ARGUMENT" --reporter relative-path)
 SWIFTLINT_EXIT_STATUS=$?
 set -e
 
