Add `verify_aws_cli_setup` to other cmds that use AWS cli
Looked for matches using

```
git gret -l aws -- bin
```

One match was in a Windows script, which I did not update because we
haven't seen AWS CLI issues in Windows yet.

Hat tip @ParaskP7 for bringing this up in
https://github.com/Automattic/a8c-ci-toolkit-buildkite-plugin/pull/162#issuecomment-2686811691

diff --git a/bin/upload_artifact b/bin/upload_artifact
--- a/bin/upload_artifact
+++ b/bin/upload_artifact
@@ -1,5 +1,11 @@
 #!/bin/bash -eu
 
+if ! "$(dirname "${BASH_SOURCE[0]}")/verify_aws_cli_setup"; then
+	echo "^^^ +++"
+	echo "AWS CLI setup check failed! Uploading the artifact would fail too."
+	exit 1
+fi
+
 # Usage
 # upload_artifact $file_path
 #
