Adjust indentation in `bin/validate_gemfile_lock`
This was done using Vim's built-in indentation for scripts, `G=gg`

diff --git a/bin/validate_gemfile_lock b/bin/validate_gemfile_lock
--- a/bin/validate_gemfile_lock
+++ b/bin/validate_gemfile_lock
@@ -3,9 +3,9 @@
 # We always need to run `bundle install` first, otherwise we can't compare
 bundle install
 
-if git status | grep modified | grep -q Gemfile.lock; then 
-	echo "Error: Gemfile.lock is not in sync – please run \`bundle install\` and commit your changes"
-	exit 1
+if git status | grep modified | grep -q Gemfile.lock; then
+  echo "Error: Gemfile.lock is not in sync – please run \`bundle install\` and commit your changes"
+  exit 1
 fi
 
 echo "Gemfile.lock is in sync"
