Update win 10 sdk tests to capture and inspect output

diff --git a/.buildkite/pipeline.yml b/.buildkite/pipeline.yml
--- a/.buildkite/pipeline.yml
+++ b/.buildkite/pipeline.yml
@@ -124,7 +124,14 @@ steps:
       - label: ":windows: install_windows_10_sdk Tests - Standard version file"
         command: |
           echo '20348' > .windows-10-sdk-version
-          bin/install_windows_10_sdk.ps1 -DryRun
+          $output = & bin/install_windows_10_sdk.ps1 -DryRun
+          $exitCode = $LASTEXITCODE
+          if ($exitCode -ne 0) {
+            echo "Unexpected failure. Exit code: $exitCode"
+            echo "Output:"
+            echo $output
+            exit 1
+          }
         agents:
           queue: windows
         notify:
@@ -133,8 +140,19 @@ steps:
 
       - label: ":windows: install_windows_10_sdk Tests - Version file with new lines"
         command: |
-          echo "20348\n\n" > .windows-10-sdk-version
-          bin/install_windows_10_sdk.ps1 -DryRun
+          echo "20348`n`n" > .windows-10-sdk-version
+          $output = & bin/install_windows_10_sdk.ps1 -DryRun
+          $exitCode = $LASTEXITCODE
+          if ($exitCode -ne 0) {
+            echo "Unexpected failure. Exit code: $exitCode"
+            echo "Output:"
+            echo $output
+            exit 1
+          }
+          if (($output -notmatch "[!] Invalid version file format") -and ($output -notmatch "Expected exactly one non-empty line")) {
+            echo "Failure message did not match expectation."
+            exit 1
+          }
         agents:
           queue: windows
         notify:
@@ -144,7 +162,18 @@ steps:
       - label: ":windows: install_windows_10_sdk Tests - Version file with a word"
         command: |
           echo "not an integer" > .windows-10-sdk-version
-          bin/install_windows_10_sdk.ps1 -DryRun
+          $output = & bin/install_windows_10_sdk.ps1 -DryRun
+          $exitCode = $LASTEXITCODE
+          if ($exitCode -ne 1) {
+            echo "Expected exit code 1, got: $exitCode"
+            echo "Output:"
+            echo $output
+            exit 1
+          }
+          if (($output -notmatch "[!] Invalid version file format") -and ($output -notmatch "Expected an integer, got:'")) {
+            echo "Failure message did not match expectation."
+            exit 1
+          }
         agents:
           queue: windows
         notify:
